// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC41xmpgv3Z1D4QSbJifU-TlA-w30RUo00',
    appId: '1:1045403779986:web:cef1e1380cd195720d374b',
    messagingSenderId: '1045403779986',
    projectId: 'carena-392620',
    authDomain: 'carena-392620.firebaseapp.com',
    storageBucket: 'carena-392620.appspot.com',
    measurementId: 'G-L3NLQJ3W1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrnQyy1Dps0q5x7qk-fFCPGy6sgKfaQs8',
    appId: '1:1045403779986:android:1ac4de8254c433fd0d374b',
    messagingSenderId: '1045403779986',
    projectId: 'carena-392620',
    storageBucket: 'carena-392620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWSzw2sTYb6OMDdx56hwRfqYV3J9B-D3Q',
    appId: '1:1045403779986:ios:ea8327a231b714bf0d374b',
    messagingSenderId: '1045403779986',
    projectId: 'carena-392620',
    storageBucket: 'carena-392620.appspot.com',
    androidClientId: '1045403779986-prjb270dpvk17dljvpvcp5j6cp5gn1ds.apps.googleusercontent.com',
    iosClientId: '1045403779986-6chv1m0po9293bv4unlfu67bb9hnu38s.apps.googleusercontent.com',
    iosBundleId: 'com.example.carena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWSzw2sTYb6OMDdx56hwRfqYV3J9B-D3Q',
    appId: '1:1045403779986:ios:66f17b4a60b7789d0d374b',
    messagingSenderId: '1045403779986',
    projectId: 'carena-392620',
    storageBucket: 'carena-392620.appspot.com',
    androidClientId: '1045403779986-prjb270dpvk17dljvpvcp5j6cp5gn1ds.apps.googleusercontent.com',
    iosClientId: '1045403779986-br65nrkbjh5mohi467iuh6leg57d3tr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.carena.RunnerTests',
  );
}
